services:
  crud:
    build: ./
    image: crud-service
    container_name: crud-service
    restart: always
    networks:
      - crud-net
    ports:
      - 80:80
    depends_on:
      - postgres
    env_file: .env
  postgres:
    env_file: .env
    image: postgres:15
    container_name: crud-psgr
    networks:
      - crud-net
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    name: postgres_db_crud
networks:
  crud-net:
    driver: bridge
